sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t luisfguzman/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true luisfguzman/react-test npm run test -- --coverage
    
after_success:
    - docker build -t luisfguzman/multi-client ./client
    - docker build -t luisfguzman/multi-nginx ./nginx
    - docker build -t luisfguzman/multi-server ./server
    - docker build -t luisfguzman/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push luisfguzman/multi-client
    - docker push luisfguzman/multi-nginx
    - docker push luisfguzman/multi-server
    - docker push luisfguzman/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-047909440977"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"